spring:
  profiles:
    active: dev

  application:
    name: backend

  # JPA 설정
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # File Upload 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# Toss Payments API URL
toss:
  payments:
    url: https://api.tosspayments.com

# Application Settings
app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:8080
